services:
  virtual-facility-db:
    image: postgres:15-alpine
    container_name: virtual-facility-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=virtual-facility
    ports:
      - '5432:5432' # Bind hosts port `5434` to container port `5432`
  workflows-db:
    image: postgres:15-alpine
    container_name: workflows-db-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workflows
    ports:
      - '5433:5432' # Bind hosts port `5433` to container port `5432`
